language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm-nightly
  - hhvm

matrix:
  allow_failures:
    - php: hhvm-nightly
    - php: hhvm

before_script:
  - composer selfupdate
  - composer install --dev --prefer-dist --no-interaction

script:
  - vendor/bin/atoum
  - phantomjs Resources/js/run_jsunit.js Resources/js/manager_test.html
